name: "Create Files"
description: "Easily Create Various Files from Templates with Custom Options."
author: "Shane"

branding:
  icon: "file-plus"
  color: "green"

inputs:
  type:
    description: "Type of File to Create"
    default: "test"
  file:
    description: "Output File to Create"
    default: "test"
  data:
    description: "File Data"
    default: "test"

outputs:
  content:
    description: "File Content"

runs:
  using: "docker"
  image: "Dockerfile"
